"use client";

import { useAppDispatch, useAppSelector } from "@/store";
import { addOne, initCountState, substractOne } from "@/store/counter/counterSlice";
import { error } from "console";
import { useEffect } from "react";

interface Props {
  value: number;
}

// Generated by https://quicktype.io
export interface CounterResponse {
  method: string;
  count:  number;
}


const getApiCounter = async ():Promise<CounterResponse> => {
  const data = await fetch('/api/counter').then( res => res.json());
  console.log(data);

  return data;
}

export const CartCounter = ( { value= 0}: Props ) => {

  const count = useAppSelector( state => state.counter.count );
  const dispatch = useAppDispatch();

  /* useEffect(() => {
    dispatch( initCountState( value))
  }, [ dispatch, value ]); */

  useEffect(() => {
    getApiCounter()
    .then( ({ count }) => dispatch( initCountState( count )));
  }, [dispatch]);
  

  return (
    <>
      <span className="text-9xl">
        {count}
      </span>

      <div className="flex">
        <button
          className="flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px] mr-2"
          onClick={() => dispatch(addOne())}
        >
          +1
        </button>

        <button
          className="flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px] mr-2"
          onClick={() => dispatch(substractOne())}
        >
          -1
        </button>
      </div>
    </>
  );
}
